### ISSUE TITLE
Bootstrap.bat not working on 1.65.0+

### ISSUE THREAD

**Issue by killerwife** [boostorg/build#236]
What I did:
Installation instruction for minimal build of boost specify this:
bootstrap
.\b2

What I got:
I ran bootstrap.bat on windows 10 with visual studio 2017 installed and this is what I received in bootstrap.log:
**********************************************************************
** Visual Studio 2017 Developer Command Prompt v15.0.26730.12
** Copyright (c) 2017 Microsoft Corporation
**********************************************************************
[vcvarsall.bat] Environment initialized for: 'x86'
###
###

C:\Users\killerwife\source>if exist bootstrap rd /S /Q bootstrap 

C:\Users\killerwife\source>md bootstrap 

C:\Users\killerwife\source>cl /nologo /RTC1 /Zi /MTd /Fobootstrap/ /Fdbootstrap/ -DNT -DYYDEBUG -wd4996 kernel32.lib advapi32.lib user32.lib /Febootstrap\yyacc0 yyacc.c 
yyacc.c
c1: fatal error C1083: Cannot open source file: 'yyacc.c': No such file or directory

What is supposed to happen?
It is supposed to go through and generate b2 for successful build.

Tested with releases:
1.64.0, 1.65.0, 1.65.1

**Comment by killerwife** [comment]
Update:
By removing vc141 in guess_toolset.bat and compiling bjam using vc14, I managed to get vc141 compilation running. It seems only the bjam compilation is broken due to some new vc141 things.

**Comment by BurningEnlightenment** [comment]
@killerwife Have you tried to execute `bootstrap.bat` from within the vs2017 native tools command prompt?

**Comment by killerwife** [comment]
@BurningEnlightenment I have not. I executed it only from powershell and cmd.exe

**Comment by BurningEnlightenment** [comment]
I can reproduce this failure with powershell and a "plain" cmd, but using the native tools command prompt does work for me, so I'm wondering whether it works for you, too. Maybe this is intentional and just poorly documented 🤔

**Comment by SSE4** [comment]
I have had a similar error, the problem is that vcvarsall.bat changes current directory to the ~/Source, e.g. in your case it is C:\Users\killerwife\source as seen in your log.
I am setting environment variable VSCMD_START_DIR prior to executing vcvarsall.bat to bypass an error, e.g. VSCMD_START_DIR=%CD%. vcvarsall.bat

**Comment by PayasR** [comment]
Tested on boost 1_65_1, I was able to compile with the dev command prompt

**Comment by Nekto89** [comment]
Have the same issue with 1.65.1 and VS2017 Update 2. It was working on 1.64.0 without problems. This seems to be working as a workaround:

[vc141_configure.patch.txt](https://github.com/boostorg/build/files/1398023/vc141_configure.patch.txt)

**Comment by DISAPPEARED13** [comment]
Hi there, I tried to use vs2017 native tools command prompt to run bootstrap.bat, but some relative problem occurs to me... when compiling the cpp file, shows that `fatal error C1083, cannot open stdint.h, no such file or directory`, I found that `tools/build/src/engine/config.h` codes `#include <stdint.h>`, and I tried to compile my random project with include the stdint.h, and succeeded. 
Why run bootstrap.h causes C1083, I have these head files...
Could anyone give me an advice!! Thanks a lot!
