### ISSUE TITLE
1.71.0 build error

### ISSUE THREAD

**Issue by neok-m4700** [boostorg/build#468]
I cannot compile boost `1.71.0` with my toolchain on LINUX ubuntu, but `1.70.0` builds fine.

The following command fails [...]
```bash
$ ./bootstrap.sh --prefix=$PREFIX --with-icu=$PREFIX --with-toolset=gcc --with-python=$PREFIX/py3/bin/python3 --with-python-root=$PREFIX/py3
Building Boost.Build engine with toolset gcc... 
Failed to build Boost.Build build engine
Consult 'bootstrap.log' for more details
```

[...] with the following errors:
**bootstrap.log**
```bash
###
###
### Using 'gcc' toolset.
###
###
g++ --version
g++ (GCC) 9.2.0
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

###
###
g++ -x c++ -std=c++11 -O2 -s -DNDEBUG builtins.cpp class.cpp command.cpp compile.cpp constants.cpp cwd.cpp debug.cpp debugger.cpp execcmd.cpp filesys.cpp frames.cpp function.cpp glob.cpp hash.cpp hcache.cpp hdrmacro.cpp headers.cpp jam.cpp jambase.cpp jamgram.cpp lists.cpp make.cpp make1.cpp md5.cpp mem.cpp modules.cpp native.cpp object.cpp option.cpp output.cpp parse.cpp pathsys.cpp regexp.cpp rules.cpp scan.cpp search.cpp strings.cpp subst.cpp sysinfo.cpp timestamp.cpp variable.cpp w32_getreg.cpp modules/order.cpp modules/path.cpp modules/property-set.cpp modules/regex.cpp modules/sequence.cpp modules/set.cpp execunix.cpp fileunix.cpp pathunix.cpp -o b2
$PREFIX/lib/gcc/x86_64-pc-linux-gnu/9.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: /tmp/ccOmdVfA.o: in function `class_module_name(_object*)':
class.cpp:(.text+0x1d): undefined reference to `string_new(string*)'
$PREFIX/lib/gcc/x86_64-pc-linux-gnu/9.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: class.cpp:(.text+0x2a): undefined reference to `string_append(string*, char const*)'
$PREFIX/lib/gcc/x86_64-pc-linux-gnu/9.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: class.cpp:(.text+0x35): undefined reference to `string_append(string*, char const*)'
$PREFIX/lib/gcc/x86_64-pc-linux-gnu/9.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: class.cpp:(.text+0x49): undefined reference to `string_free(string*)'
<...>
```
**toolchain**
glibc `2.30`
gcc `9.2.0`
binutils `2.32`
python `3.7.4`
icu `64.2`

**Comment by grafikrobot** [comment]
It work with the similar gcc 9.1 on Ubuntu 16.04.. https://dev.azure.com/grafikrobot/B2/_build/results?buildId=322&view=logs&jobId=ab7f25a7-b5a5-579d-a20f-21af88c4eab1&taskId=a66d6b7d-affd-559a-e342-4b52a5b48225&lineStart=18&lineEnd=19&colStart=1&colEnd=1

**Comment by crillion** [comment]
same problem on windows 10 / msys2 / mingw-w64 : error on building b2. also noted that it doesn't use my system's gcc (9.2.0, as specified in the PATH environment variable), but it finds an older version (6.3) which had remained on my system from an older mingw-w64 installation (not with msys2).

**Comment by Lastique** [comment]
Same problem here, on Kubuntu 19.04, gcc 8.3.

**Comment by Lastique** [comment]
Apparently, the problem is that `string_*` declarations are declared as `extern "C"` and therefore are mangled according to C rules, not C++. I checked this by separately compiling every .cpp file. This happens because `strings.h` file where these functions are declared, clashes names with the system header `strings.h`, which gets indirectly included by other system headers within an `extern "C"` region. For example, `/usr/include/string.h` can include `<strings.h>` under some conditions.

I'm not sure why this doesn't trigger reliably in CI or in my git checkout. Possibly, include search order is not fully deterministic in gcc, if the same-named headers are found in multiple locations.

**Comment by neok-m4700** [comment]
I agree witht the system includes, I had some paths set in `CPLUS_INCLUDE_PATH`. Still wonder what triggers this change between `1.70.0` and `1.71.0` ...

This worked for me:
```bash
(unset CPLUS_INCLUDE_PATH; ./bootstrap.sh <...>)

./b2 <...> -j$(nproc) install
```

**Comment by Lastique** [comment]
`CPLUS_INCLUDE_PATH` is not set in my case. It broke in 1.71 because in previous releases `b2` was written in C, so the name mangling happened to match the system headers.
